### ISSUE TITLE
Frontend/Backend Routes

### ISSUE THREAD

**Issue by AdamYLiang** [wfragoso02/NextUp#4]
### Frontend Routes
- [x] `/` should be a Splash page
- [x] Should have a route for showing the video index 

### Backend Routes
- [ ] Need API endpoints for `My List` 

**Users** 
- [x]  `users` table shouldn't be handling sign in 

**Videos**
- [x] Should have a route to get all videos (index)

Let me know if you have any questions or want to talk about any of these!

**Comment by wfragoso02** [comment]
I have a question regarding the video index page you requested. 
As of now the videos dont exists on their own, they are a product of the genres.
I think I need some more detail as to why I should have a frontend route for the video index themselves.
